rm -rf ffmpeg-3.2.14/.config
rm -rf ffmpeg-3.2.14/.version
rm -rf ffmpeg-3.2.14/config.asm
rm -rf ffmpeg-3.2.14/config.fate
rm -rf ffmpeg-3.2.14/config.h
rm -rf ffmpeg-3.2.14/config.log
rm -rf ffmpeg-3.2.14/config.mak
rm -rf ffmpeg-3.2.14/doc/config.texi
rm -rf ffmpeg-3.2.14/doc/examples/pc-uninstalled/
rm -rf ffmpeg-3.2.14/ffmpeg_g.ilk
rm -rf ffmpeg-3.2.14/ffprobe_g.ilk
rm -rf ffmpeg-3.2.14/libavcodec/bsf_list.c
rm -rf ffmpeg-3.2.14/libavcodec/libavcodec.pc
rm -rf ffmpeg-3.2.14/libavdevice/libavdevice.pc
rm -rf ffmpeg-3.2.14/libavfilter/libavfilter.pc
rm -rf ffmpeg-3.2.14/libavformat/libavformat.pc
rm -rf ffmpeg-3.2.14/libavformat/protocol_list.c
rm -rf ffmpeg-3.2.14/libavutil/avconfig.h
rm -rf ffmpeg-3.2.14/libavutil/ffversion.h
rm -rf ffmpeg-3.2.14/libavutil/libavutil.pc
rm -rf ffmpeg-3.2.14/libswresample/libswresample.pc
rm -rf ffmpeg-3.2.14/libswscale/libswscale.pc
